services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/lib/mysqlwe
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - first-network

  api-rocket:
    container_name: api-rocket
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - first-network

networks:
  first-network:
    name: first-network
    driver: bridge
  
volumes:
  db: 
  